/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./src/assets/menu.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import menu from '../assets/menu.glb'

export function Menu(props) {
  const { nodes, materials } = useGLTF(menu)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text_Exp.geometry} material={materials['Material.003']} position={[-2.149, -0.212, 2.293]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Text_Home.geometry} material={materials.Material} position={[-2.327, 0, 0.411]} rotation={[Math.PI / 2, 0, 1.568]} />
      <mesh geometry={nodes.Text_About.geometry} material={materials['Material.002']} position={[2.395, 0, 0]} rotation={[Math.PI / 2, 0, -1.574]} />
      <mesh geometry={nodes.TextContact.geometry} material={materials['Material.001']} position={[0, 0, -2.443]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Portal_About.geometry} material={materials['Material.002']} position={[4.289, 0, 0]} scale={[0.25, 1.101, 2.474]} />
      <mesh geometry={nodes.Portal_Contact.geometry} material={materials['Material.001']} position={[0, 0, -0.312]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 1.181, 2.288]} />
      <mesh geometry={nodes.Portal_Exp.geometry} material={materials['Material.003']} scale={[1.539, 0.758, 1]} />
      <mesh geometry={nodes.Portal_Home.geometry} material={materials.Material} rotation={[Math.PI, 0, Math.PI]} scale={[0.25, 1.382, 2.319]} />
      <mesh geometry={nodes.Cube_cell.geometry} material={materials.Material} position={[0.341, 0.36, -0.702]} />
      <mesh geometry={nodes.Cube_cell001.geometry} material={materials.Material} position={[0.356, -0.37, -0.695]} />
      <mesh geometry={nodes.Cube_cell002.geometry} material={materials.Material} position={[0.71, 0.39, 0.663]} />
      <mesh geometry={nodes.Cube_cell003.geometry} material={materials.Material} position={[0.48, -0.662, 0.459]} />
      <mesh geometry={nodes.Cube_cell004.geometry} material={materials.Material} position={[-0.594, 0.558, -0.831]} />
      <mesh geometry={nodes.Cube_cell005.geometry} material={materials.Material} position={[-0.939, -0.592, -0.341]} />
      <mesh geometry={nodes.Cube_cell006.geometry} material={materials.Material} position={[-0.712, 0.652, 0.781]} />
      <mesh geometry={nodes.Cube_cell007.geometry} material={materials.Material} position={[0.904, -1, -0.536]} />
      <mesh geometry={nodes.Cube_cell008.geometry} material={materials.Material} position={[-0.54, -0.614, 0.009]} />
      <mesh geometry={nodes.Cube_cell009.geometry} material={materials.Material} position={[0.036, -0.823, -0.783]} />
      <mesh geometry={nodes.Cube_cell010.geometry} material={materials.Material} position={[0.934, -0.423, -0.83]} />
      <mesh geometry={nodes.Cube_cell011.geometry} material={materials.Material} position={[-0.707, -0.075, 0.4]} />
      <mesh geometry={nodes.Cube_cell012.geometry} material={materials.Material} position={[0.576, -0.086, 0.572]} />
      <mesh geometry={nodes.Cube_cell013.geometry} material={materials.Material} position={[-1.046, 0, -0.689]} />
      <mesh geometry={nodes.Cube_cell014.geometry} material={materials.Material} position={[0.017, 1.004, 1.084]} />
      <mesh geometry={nodes.Cube_cell015.geometry} material={materials.Material} position={[0.944, 0.554, -0.244]} />
      <mesh geometry={nodes.Cube_cell016.geometry} material={materials.Material} position={[-0.036, -0.581, 0.869]} />
      <mesh geometry={nodes.Cube_cell017.geometry} material={materials.Material} position={[-0.727, 0.535, -0.019]} />
      <mesh geometry={nodes.Cube_cell018.geometry} material={materials.Material} position={[-0.033, 0.781, -0.634]} />
      <mesh geometry={nodes.Cube_cell019.geometry} material={materials.Material} position={[0.569, -0.574, -0.02]} />
      <mesh geometry={nodes.Cube_cell020.geometry} material={materials.Material} position={[-0.012, 0.71, 0.013]} />
      <mesh geometry={nodes.Cube_cell021.geometry} material={materials.Material} position={[-0.199, -0.117, 0.703]} />
      <mesh geometry={nodes.Cube_cell022.geometry} material={materials.Material} position={[-1.411, 0.211, -0.013]} />
      <mesh geometry={nodes.Cube_cell023.geometry} material={materials.Material} position={[0.012, -1.293, 0.402]} />
      <mesh geometry={nodes.Cube_cell024.geometry} material={materials.Material} position={[1.28, -0.015, 0.012]} />
      <mesh geometry={nodes.Cube_cell025.geometry} material={materials.Material} position={[-0.011, -0.014, -1.357]} />
    </group>
  )
}

useGLTF.preload(menu)
